repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.7
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, duckdb, --config, .sqlfluff]
        additional_dependencies:
          - sqlfluff-templater-dbt==3.0.7
      - id: sqlfluff-fix
        args: [--dialect, duckdb, --config, .sqlfluff]
        additional_dependencies:
          - sqlfluff-templater-dbt==3.0.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
